import type { Category, Product, Coupon } from './types';

export const categories: Category[] = [
  { id: 'birthday-gifts', name: 'Birthday Gifts', image: 'cat-birthday', offer: 'Up to 20% Off' },
  { id: 'anniversary-gifts', name: 'Anniversary Gifts', image: 'cat-anniversary' },
  { id: 'wedding-gifts', name: 'Wedding Gifts', image: 'cat-wedding', offer: 'Free Gift Wrap' },
  { id: 'for-her', name: 'For Her', image: 'cat-for-her' },
  { id: 'for-him', name: 'For Him', image: 'cat-for-him' },
  { id: 'personalized-gifts', name: 'Personalized Gifts', image: 'cat-personalized' },
  { id: 'kids-gifts', name: 'Kids Gifts', image: 'cat-kids' },
  { id: 'corporate-gifts', name: 'Corporate Gifts', image: 'cat-corporate' },
  { id: 'festival-gifts', name: 'Festival Gifts', image: 'cat-festival' },
];

export const products: Product[] = [
  {
    id: 'artisan-chocolate-box',
    name: 'Artisan Chocolate Box',
    description: 'A luxurious collection of hand-crafted chocolates.',
    longDescription: 'Indulge their senses with this exquisite selection of 24 artisan chocolates. Each piece is hand-crafted by master chocolatiers using the finest single-origin cacao. Flavors include sea salt caramel, raspberry ganache, and hazelnut praline. Beautifully packaged and ready for gifting.',
    price: 45.00,
    category: 'for-her',
    images: ['prod-1-1', 'prod-1-2'],
    rating: 4.9,
    reviews: 124,
  },
  {
    id: 'hand-poured-soy-candle',
    name: 'Hand-Poured Soy Candle',
    description: 'Scented candle for a relaxing ambiance.',
    longDescription: 'Create a serene atmosphere with our hand-poured soy candle. Made with 100% natural soy wax and premium fragrance oils, this candle offers a clean, long-lasting burn of up to 50 hours. The "Sandalwood & Vanilla" scent is warm, comforting, and perfect for unwinding after a long day.',
    price: 28.00,
    category: 'for-her',
    images: ['prod-2-1', 'prod-2-2'],
    rating: 4.8,
    reviews: 98,
  },
  {
    id: 'premium-leather-journal',
    name: 'Premium Leather Journal',
    description: 'A classic journal for thoughts and ideas.',
    longDescription: 'For the writer, dreamer, or planner, this premium leather journal is an inspiring companion. Featuring a soft, genuine leather cover and 200 pages of thick, acid-free lined paper, it\'s perfect for capturing thoughts, sketches, and plans. An elastic band keeps it securely closed.',
    price: 35.00,
    category: 'for-him',
    images: ['prod-3-1', 'prod-3-2'],
    rating: 4.9,
    reviews: 210,
  },
  {
    id: 'minimalist-silver-necklace',
    name: 'Minimalist Silver Necklace',
    description: 'Elegant and timeless sterling silver necklace.',
    longDescription: 'This minimalist necklace embodies elegance in simplicity. Crafted from polished 925 sterling silver, the delicate chain features a small, geometric pendant that catches the light beautifully. It\'s a versatile piece, perfect for everyday wear or for layering with other necklaces.',
    price: 65.00,
    category: 'for-her',
    images: ['prod-4-1', 'prod-4-2'],
    rating: 4.7,
    reviews: 75,
  },
   {
    id: 'quirky-coffee-mug',
    name: 'Quirky Coffee Mug',
    description: 'Start the day with a smile and a fun mug.',
    longDescription: 'Brighten up their morning routine with this quirky and fun coffee mug. Made from durable ceramic, it holds 12oz of their favorite beverage. The witty phrase printed on the side is sure to bring a smile to their face. It\'s both dishwasher and microwave safe.',
    price: 18.50,
    category: 'personalized-gifts',
    images: ['prod-5-1'],
    rating: 4.6,
    reviews: 150,
  },
   {
    id: 'mens-grooming-kit',
    name: 'Men\'s Grooming Kit',
    description: 'All-in-one kit for the modern gentleman.',
    longDescription: 'This complete grooming kit has everything he needs to look and feel his best. It includes a natural beard oil, a firm-hold styling balm, a sandalwood-scented face wash, and a moisturizing lotion. All products are made with natural ingredients and come in a stylish travel bag.',
    price: 49.99,
    category: 'for-him',
    images: ['prod-6-1'],
    rating: 4.8,
    reviews: 88,
  },
  {
    id: 'celebration-gift-box',
    name: 'Celebration Gift Box',
    description: 'A festive box for any special occasion.',
    longDescription: 'Mark a special milestone with this curated Celebration Gift Box. It includes a mini bottle of sparkling wine, two champagne flutes, gourmet popcorn, and a festive confetti popper. It\'s the perfect way to say "Congratulations!" or "Happy Birthday!".',
    price: 55.00,
    category: 'birthday-gifts',
    images: ['prod-1-1', 'prod-1-2'],
    rating: 4.9,
    reviews: 63,
  },
   {
    id: 'spa-day-essentials',
    name: 'Spa Day Essentials',
    description: 'A relaxing at-home spa experience.',
    longDescription: 'Give the gift of relaxation with this at-home spa kit. It includes a lavender bath bomb, a calming facial mask, luxurious body butter, and a soft exfoliating cloth. It\'s the perfect way to unwind and de-stress.',
    price: 42.00,
    category: 'for-her',
    images: ['prod-2-1'],
    rating: 4.7,
    reviews: 112,
  },
];

export const coupons: Coupon[] = [
  {
    code: 'GIFT10',
    type: 'percentage',
    value: 10,
  },
  {
    code: 'SAVE20',
    type: 'flat',
    value: 20,
    minimumCartValue: 50,
  }
];
